### ISSUE TITLE
URL invalide dans le README

### ISSUE THREAD

**Issue by elainesoucy** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#100]
Le 2e point amène sur une page 404 dans le README (point Information sur le squelette)

![image](https://user-images.githubusercontent.com/46898201/133950035-511871b0-0c02-4435-9067-6ef4f0caf72a.png)

**Comment by fuhrmanator** [comment]
Merci pour l'Issue! J'ai corrigé dans le dépôt de base, mais si une équipe a déjà cloné, la solution est de changer l'URL à `Squelette.md` (S majuscule).

**Comment by fuhrmanator** [comment]
Je mets en place une action Github pour vérifier les urls des markdown automatiquement
