### ISSUE TITLE
Utilisation des issues

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#104]
Spécifier aux étudiants qu'ils peuvent créer des issues et nous les associés pour que nous puissions améliorer le laboratoire.

**Comment by fuhrmanator** [comment]
Dans les énoncés du lab1, c'est assez explicite:

> # Système de gestion de l'apprentissage
> Version: Automne 2021 (1.0.1)
> Si vous trouvez des incohérences ou vous avez des questions, créez un [Issue](new/choose).

Mais on peut aussi le faire dans la doc du squelette.
