### ISSUE TITLE
PUG vs HTML

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#109]
Permettre l'utilisation de html au lien de PUG.

**Comment by yvanross** [comment]
documenté dans les exigences.

**Comment by fuhrmanator** [comment]
Le nouveau squelette intègre une barre de navigation Bootstrap avec des routes pour /signin, /signout et des différences de pages (mixin) selon un type d'utlisateur. Alors, je crois qu'il faut encourager les gens à l'utiliser surtout pour le lab 1 avec Enseignant/Etudiant et les connexions.
