### ISSUE TITLE
Find replacement for Flask-like flashing (node-twinkle)

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#11]
node-twinkle has not been updated for 6+ years and it has security flaws.

Try to find a replacement to it, and update the skeleton accordingly. 

A useful search query:  https://www.npmjs.com/search?q=express%20flash%20message

Maybe https://www.npmjs.com/package/express-flash-message is a good candidate?

**Comment by yvanross** [comment]
wontfix - not a production project.
