### ISSUE TITLE
Dead links dans docs/Squelette.md

### ISSUE THREAD

**Issue by Leuchak** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#120]
L'action Markdown Link Check échoue avec l'erreur suivante:
> ERROR: 2 dead links found!
> [✖] https://restfulapi.net/richardson-maturity-model/#level-two → Status: 503
> [✖] https://restfulapi.net/richardson-maturity-model/#level-three → Status: 503

Les liens fonctionnent, j'ignore pourquoi github obtient une erreur 503.

**Comment by fuhrmanator** [comment]
Résolu dans un autre PR #124
