### ISSUE TITLE
Intégrer plusieurs verbes REST

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#15]
Pour l'instant le squelette utilise toujours HTTP GET, mais il serait bien de montrer un cas (logique) d'utilisation de POST avec des arguments passés. Par contre, ça risque de compliquer trop le lab sur le volet Web. Ça devrait être facultatif.

**Comment by Olon11** [comment]
Veux-tu dire POST plutôt que PUT? On pourrait utiliser POST pour démarrerJeu afin de créer le joueur

**Comment by fuhrmanator** [comment]
@Olon11 j'ai corrigé. Oui, démarrerJeu est un bon exemple
