### ISSUE TITLE
Déplacer (ou faire les copies) du dépôt dans une autre organisation pour GitHub Classroom

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#151]
Voir les détails dans https://github.com/orgs/community/discussions/127455/

**Si j'ai bien compris**, il y aura une nouvelle contrainte que le "starter code" d'un devoir dans Classrooms se trouve dans la même organisation que la Classroom.

Actuellement, j'utilise https://github.com/ets-log210 comme organisation pour mes classrooms, mais le dépôt actuel, ainsi que les énoncés sont dans https://github.com/profcfuhrmanets

La raison que je ne place pas les dépôts (de base) dans la même organisation que les classrooms et que les TA (chargé.e.s de lab) doivent avoir les permissions de "Owner" dans l'organisation de classrooms (pour pouvoir télécharger et corriger les travaux), et c'est un risque. 

Une solution serait de générer une copie du dépôt (p-e avec squashed commits) à chaque session dans l'organisation utilisée pour classrooms (ets-log210). 

La nouvelle politique commence le 1er juillet 2024 (selon la discussion citée plus haut), donc ça doit fonctionner pour l'automne 2024.

**Comment by fuhrmanator** [comment]
Voici une copie des points mentionné dans la discussion:

> - Classroom will require that your provided starter code is a template repository. When you create your assignment, Classroom will create a new repository from the template with the visibility you select, and use THAT as the base from which student repositories will be forked. This will reinstate your ability to choose assignment visibility when you create a new assignment.
> - Classroom will not give students "read" permissions to the upstream starter code repository; instead, teachers will have a button on the assignment dashboard in Classroom that will check for changes and open Pull Requests in all student repositories. Students can then accept the changes from their own repositories. This prevents any possibility of students opening pull requests upstream where their work is revealed to other students
> - Classroom will inform you if forking private repositories is turned off for your organization when you select "Private" visibility for your assignment. If you choose to continue, Classroom will automatically change this setting in your classroom's GitHub organization
> - Classroom will give you the choice to copy all branches to student assignment repositories, or just the default branch

**Comment by fuhrmanator** [comment]
Au fait, j'ai l'impression qu'on aurait dû mettre en place la politique cet été. https://github.com/orgs/community/discussions/130889 -- le "dashbord" ne fonctionne plus depuis le 1er juillet, mais les chargés de lab peuvent cloner et accéder aux dépôts avec la ligne de commande `gh`.

**Comment by Olon11** [comment]
Je suis d'accord. Ce n'était pas clair que ça allait affecter les dépôts déjà clonés. Je vais regarder ça avant le 31 juillet, car je ne serai plus disponible jusqu'à septembre après cette date.

**Comment by Olon11** [comment]
Je viens de vérifier et ça ne semble pas nécessaire que le code de base soit dans la même organisation que les dépôts des étudiants. J'ai pu créer une classe dans ets-log210 avec le jeu de dés qui est dans profcfuhrmanets. GitHub a créé une copie du dépôt dans etslog210 et le fork a été fait à partir de ce dépôt.

Tu peux confirmer ici : https://classroom.github.com/classrooms/61713053-test-new-changes-to-github-classroom

**Comment by fuhrmanator** [comment]
Sauf que personne n'a commencé l'assignment. Je ne pense pas que ton test soit adéquat.

Le problème que j'ai signalé depuis le 1er juillet est vraiment relié aux permissions. Le dashboard essaie d'accéder aux dépôts pour afficher le nombre de commits, etc. 

Pourquoi GitHub ferait tout un blogue et envoyer les courriels pour nous avertir du changement pour rien?

**Comment by Olon11** [comment]
J'ai créé une équipe, un travail et je viens de faire un commit. Je n'ai pas le bug dont tu parles. En fait, je ne vois même pas les classes de cet été sur GitHub Classroom pour reproduire le bug. Elles sont bien dans etslog210?

> Pourquoi GitHub ferait tout un blogue et envoyer les courriels pour nous avertir du changement pour rien?

J'ai compris que c'était un irritant durant la beta et que le problème a été réglé en faisant une copie du dépôt dans l'organisation où les travaux sont clonés : https://github.com/ets-log210/test-new-changes-to-github-classroom-test-labo-log210-jeu-de-des-node-express-ts

Cette copie a été "generated from" le jeu de dés dans profcfuhrmanets, alors que le travail étudiant que j'ai créé a été "forked from" la copie.

**Comment by Olon11** [comment]
@probitaille Finalement, est-ce que ça fonctionne? On peut fermer l'issue?

**Comment by Olon11** [comment]
Selon Patrice :

> Je n'ai pas eu de problème, jusqu'à maintenant. 😉
