### ISSUE TITLE
Déplacer les vues dans une classe à part (routeur)

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#156]
Les routes `/`, `/signin` et `/signout` devraient être dans un routeur à part pour améliorer la cohésion de `App`.

**Comment by fuhrmanator** [comment]
Encore, ça rend plus facile un issue quand tu mets des liens vers les fichiers sources.

**Comment by Olon11** [comment]
https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/master/src/app.ts#L52

**Comment by fuhrmanator** [comment]
En principe, je suis d'accord. Cependant, le but d'un squelette est d'avoir un solution (simple) qui est relativement facile à comprendre. `/signin` et `/signout` sont très courts et montrent bien l'intégration avec PUG, etc. Si c'est dans un autre fichier, ça rend le code plus complexe à comprendre. 

Peut-on écrire un commentaire pour indiquer que la logique plus complexe pour ces choses devrait se trouver dans un routeur à part? C'est une refactorisation que les étudiants doivent faire lorsque leur code grossit.

**Comment by Olon11** [comment]
Il y a déja un routeur dans une classe externe à la ligne 96. Je ne vois pas pourquoi ça complique les choses d'en avoir un autre.

**Comment by fuhrmanator** [comment]
> Si c'est dans un autre fichier, ça rend le code plus complexe à comprendre.

Autrement dit, c'est plus difficile s'il faut ouvrir un autre fichier pour comprendre la logique (qui est moins de 20 lignes pour les deux endpoints je crois).

Martin Fowler explique dans la partie "Inline function" de son livre Refactorings:

> I commonly use Inline Function when I see code that's using too much indirection—when it seems that every function does simple delegation to another function, and I get lost in all the delegation. 

Les nouveaux étudiants et étudiantes sont susceptibles de se perdre, alors gardons ça "inline" pour le squelette avec une recommandation de déléguer (comme c'est le cas pour l'API, puisque la logique est plus complexe).
