### ISSUE TITLE
Optimiser la RDCU pour jouer

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#17]
brasser() doit retourner la valeur du dé pour éviter d'avoir à la récupérer par la suite.

- [ ] Modifier la RDCU
- [ ] Modifier le code

**Comment by fuhrmanator** [comment]
Pas d'accord... https://martinfowler.com/bliki/CommandQuerySeparation.html

**Comment by Olon11** [comment]
L'idée c'est de garder quand même `getValue()`, mais `brasser()` retourne aussi la valeur pour être plus pratique. Comme tu veux...

**Comment by fuhrmanator** [comment]
Ok, cela a l'aire banal. Puis dans la couverture des tests, `getValue()` va apparaître comme dead code parce qu'on ne s'en sert plus. Alors, on supprime la méthode, puis... ? https://stackoverflow.com/questions/26902137/why-does-the-cqs-principle-require-a-command-not-to-return-any-value

Larman explique le cas avec les dés dans le chapitre 18 en anglais... Je préfère suivre la théorie pour un cours axé sur la conception.
