### ISSUE TITLE
Améliorer la gestion des erreurs

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#18]
Utiliser des classes d'erreurs personnalisées pour gérer les erreurs HTTP et réduire la quantité de code dans le routeur

**Comment by fuhrmanator** [comment]
Je veux bien approuver, mais je voudrais voir une preuve que c'est plus simple. As-tu un exemple fait par une équipe?

**Comment by Olon11** [comment]
J'ai un exemple fait dans mes propres projets. Ça évite d'avoir à comparer des messages d'erreur pour trouver le code HTTP comme dans le squelette actuel.

Classe d'erreur :

```
class NotFound extends Error {
    private _code:number = NaN;

    constructor(message:string) {
        super(message);
        this._code = 404;
    }

    get code():number {
        return this._code;
    }
}
```

Utilisation :
```
try {
    ...
}
catch (error) {
    res.status(error.code).json({ error: error.message });
}
```

**Comment by fuhrmanator** [comment]
`NotFoundError` est un meilleur nom, selon moi.

Tu devrais dans ce cas suivre les directives sur les patterns des exceptions (A35/F30 du livre) - bien nommer les exceptions et utiliser le pattern "convertir les exceptions" - ça serait encore plus cool si tu mettais les références à la section du livre dans les commentaires 👍  

Puis, as-tu beaucoup utilisé ce pattern dans TypeScript? J'ai trouvé cet avertissement: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

Sinon, s'il manque de temps tu peux proposer cela comme exercice avec @yvanross ?

**Comment by Olon11** [comment]
Je vais regarder ces liens. J'ai déjà utilisé cette gestion des erreurs, mais je n'ai jamais eu de problèmes. Peut-être que c'est uniquement dans les vieux navigateurs?

**Comment by Olon11** [comment]
J'ai lu le chapitre du livre et je me demandais la pertinence, dans un projet aussi simple, d'avoir plusieurs couches d'erreurs. Ça devient compliqué pour rien. Sinon, ma solution semble respecter le contenu du chapitre.

**Comment by fuhrmanator** [comment]
Je pense qu'on parle de la même chose.

Par exemple https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/06a41ae06838bbb05cc99de96bc860ff3b4c1b99/src/core/JeuDeDes.ts#L31

Lancer une erreur JoueurNonTrouvé donne plus de contexte à la "couche" qui utilise le contrôleur. 

https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/06a41ae06838bbb05cc99de96bc860ff3b4c1b99/src/routes/JeuRouter.ts#L37

La couche Routeur qui reçoit ça peut convertir l'erreur éventuellement (dans ce cas il ne relance pas une nouvelle erreur comme dans le pattern de Larman, mais il convertit en erreur 400). Tu vois l'idée?

**Comment by Olon11** [comment]
Oui, en effet. Mais je veux aussi retirer le besoin de faire la conversion puisque le code est contenu dans l'erreur.

**Comment by fuhrmanator** [comment]
Tu peux faire les deux avec l'extension.
