### ISSUE TITLE
Mettre à jour les bibliothèques de test

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#19]
Utiliser les bibliothèques jest, ts-jest et supertest. L'objectif est de rendre les tests plus faciles à comprendre pour les étudiants.

**Comment by fuhrmanator** [comment]
J'aime l'idée de simplifier, à condition qu'on arrive à faire les même tests (c'était pas évident avec Mocha...)

**Comment by Olon11** [comment]
Ce n'est pas un problème. Il faut mettre à jour les tests, mais la logique reste la même. Je le ferai en dernier puisque ça ne presse pas.
