### ISSUE TITLE
Faire une vraie map pour les joueurs

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#22]
Faire une Map à part qui peut être réutilisée. Permet aussi de faciliter la gestion des erreurs.

**Comment by fuhrmanator** [comment]
Peux-tu me donner un exemple de réutilisation? Erreur? Le principe KISS s'applique dans le squelette.

**Comment by Olon11** [comment]
C'est difficile de faire un exemple sans faire le code. La map est transformée en classe et elle possède des méthodes pour chercher, ajouter, supprimer. La gestion des erreurs est faite dans ces méthodes. Le code reste simple, mais beaucoup plus cohésif. Il y a moins de logique dans la classe JeuDeDés.

**Comment by fuhrmanator** [comment]
Je ne vois pas comment une nouvelle classe sera beacoup plus simple qu'une `Map<TypeClé, TypeObjet>`:
chercher : `get()` 
ajouter : `set()`
supprimer : `delete()`

Si tu vois que les étudiants ont une logique qui se répète à chaque utilisation de map de base, alors il peuvent appliquer un refactoring? Je préfère encore que tu montres un cas plutôt que faire la [Speculative Generality](https://refactoring.guru/smells/speculative-generality)

**Comment by Olon11** [comment]
Je ferai un exemple plus tard, puisque ce sera plus clair. Dans le jeu de dés, l'avantage est moindre (mais toujours là) que dans le projet de session.

**Comment by Olon11** [comment]
> **Edit:** Tu peux même rechercher cette refactorisation si le problème se présente à chaque session, c'est mieux que les étudiants reconnaissent la répétition comme un smell et qu'ils applique le refactoring, que de résoudre le problème dans le squelette. Le but initial du squelette est de mettre en place une solution avec le framework web (Node express) et test (Mocha, etc.).

Je peux faire ça, mais ça va se perdre avec les autres chargés. Peut-être faire un guide de correction pour les itérations?

**Comment by fuhrmanator** [comment]
Refactorisations p-e un élément de la grille pour itérations 1,2,3
