### ISSUE TITLE
Le script start:watch ne fonctionne pas correctement

### ISSUE THREAD

**Issue by obrassard** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#26]
Bonjour, j'ai remarqué que le script `start:watch` ne fonctionnait pas correctement. Tout d'abord, le package `nodemon` n'est pas inclus comme dépendance de développement dans `package.json`, de plus la configuration de nodemon pourrait être améliorée puisque le code TypeScript n'est pas recompilé suite à une modification.

J'ai fait une pull request (#27) pour adresser le problème !

**Comment by fuhrmanator** [comment]
Merci! Je regarde ça demain.
