### ISSUE TITLE
Retirer jQuery

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#28]
La bibliothèque de code n'est plus nécessaire avec des navigateurs modernes. Cela fera une bibliothèque de moins à apprendre aux étudiants.

**Comment by yvanross** [comment]
Il faudrait réécrire entièrement main.js  puisqu'il utilise des requêtes jquery $.

**Comment by Olon11** [comment]
C'est déjà fait, mais j'attendais la fin du clonage des repo pour merge le repo.

**Comment by fuhrmanator** [comment]
@Olon11 le PR a des conflits sur public/lib/main.js -- peux-tu les corriger et puis je peux faire le merge.

**Comment by fuhrmanator** [comment]
C'est fait - j'ai utilisé entièrement ta version @Olon11
