### ISSUE TITLE
Modifier le lien pour la grille de correction des rapports

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#30]
Je suis propriétaire de fichier. Il faudrait que soit Christopher ou Yvan fasse une copie. Par la suite, on remplace le lien vers la copie dans le gabarit du rapport.

**Comment by yvanross** [comment]
Quels fichiers?

**Comment by Olon11** [comment]
La grille de correction dans le rapport. https://docs.google.com/spreadsheets/d/1KKGPxac13vHttuC2AQDpRrgLuirMU0kd3qFxc9qhOuk

**Comment by fuhrmanator** [comment]
Pourrais-tu faire un PR @Olon11 (j'ignore exactement où est le lien à changer)

**Comment by yvanross** [comment]
J'ai fait la copie et ajouter le lien vers celle ci dans l'énoncé du laboratoire.
