### ISSUE TITLE
  Ajouter des taches pour creer une nouvelle page de vue dans le lab0.  

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#34]

**Comment by Olon11** [comment]
Je ne vois pas vraiment l'intérêt d'une tâche de ce genre, puisqu'il y a un exemple dans le dépôt des exemples de code. C'est aussi une tâche triviale.

**Comment by yvanross** [comment]
Je suis d'accord.
