### ISSUE TITLE
Séparer le backend du front end dans l'évaluation des CU

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#41]
Obliger les étudiants à séparer les tâches de front-end et de backend.  Il peuvent ainsi implémenté l'api à l'itération 1 et le front-end à l'itération 2. Les chargés de laboratoire devront validé indépendamment les backend et les front-end.  En commencant par le backend.  Ils vérifient le front-end uniquement lorsque le backend fonctionne adéquatement.

**Comment by fuhrmanator** [comment]
Quelle est la motivation de ce changement? La simplicité du projet "web" est importante dans LOG210, surtout qu'il y a d'autres cours qui vont faire du web. Il est vrai que l'industrie fait souvent la séparation, mais c'est encore une autre dimension à comprendre. Je ne suis pas contre mais les bénéfices par rapport à la complexification doivent être évidentes.

**Comment by fuhrmanator** [comment]
Je rajoute un point -- il est difficile d'imaginer un cas d'utilisation (dans le sens traditionnel, à la Larman) sans frontend.

**Comment by yvanross** [comment]
L'objectif ici est uniquement de permettre aux étudiants de ne pas nécessairement remettre l'implémentation d'un CU complet (front-end et backend) dans une seule itération.  Cela concerne l'implémentation pas l'analyse et la conception.   On peut implémenter les opérations systèmes avec les test dans une itération, et le front-end dans la suivante...

**Comment by fuhrmanator** [comment]
Oui, mais ce n'est pas fidèle au principe dune itération selon le processus unifié de ne pas tout faire, n'est-ce pas? Enfin j'essaie de faire l'équilibre entre les points forts et faibles de ce choix.

**Comment by Olon11** [comment]
Ce choix provient d'un problème qu'on rencontre chez les étudiants. Ils ne comprennent pas que le front-end est indépendant du backend. La plupart testent avec leur interface et font les tests à la fin. Il manque aussi une validation back-end des paramètres HTTP et de la logique du domaine. Si on trouve une solution à ces problèmes, ce n'est plus nécessaire de faire cela.

**Comment by fuhrmanator** [comment]
> Ce choix provient d'un problème qu'on rencontre chez les étudiants. Ils ne comprennent pas que le front-end est indépendant du backend. 

Est-ce un problème grave, et si oui, pourquoi? Mon point plus haut est de dire qu'il faut simplifier l'aspect Web de toutes les façons, car on veut que les étudiants se concentrent plus sur l'aspect Analyse et Conception OO. 

> La plupart testent avec leur interface et font les tests à la fin. Il manque aussi une validation back-end des paramètres HTTP et de la logique du domaine. Si on trouve une solution à ces problèmes, ce n'est plus nécessaire de faire cela.

Une solution est d'augmenter les points pour les tests du back-end (ou pénaliser si les tests du back-end ne roulent pas). Je préfère essayer d'autres tactiques que de ne pas respecter tout le développement dans une itération normale (surtout qu'on leur donne un squelette).

**Comment by Olon11** [comment]
Je crois qu'il y a une confusion. En bref :

Problèmes identifiés :
P1 : les étudiants ne comprennent pas que le frontend est indépendant du backend
P2 : les étudiants font leurs tests après l'implémentation

Est-ce que c'est grave?
P1 : Oui. C'est un des principes de la séparation des couches. Lorsqu'on comprend cela, on évite de faire des erreurs telles que ne pas faire des validations backend ou faire des applications qui contrôlent la vue. J'ai déjà vu des étudiants qui ajoutent des variables dans le modèle pour contrôler des menus ou pour ce souvenir du dernier cours sélectionné.

P2 : Oui. Les étudiants font leurs tests, mais après avoir tous codé. Ils doivent prendre l'habitude de les faire au fur et à mesure.

Solution proposée :

Les étudiants font le backend avant, puis le frontend. Cela règle les deux problèmes. À la limite, pour P1, on peut expliquer aux étudiants le principe (en théorie ou en labo) et ça passe bien. Mais pour P2, je ne vois pas comment les forcer à faire leurs tests au fur et à mesure d'une autre façon. Ce n'est pas à cause des points. Ils les font, mais après, parce qu'ils ne considèrent pas que c'est important. Ce n'est pas ça le principe vu dans le cours.

La solution n'implique pas de changement dans l'évaluation, dans la rétroaction ou dans les indicateurs du BCAPG.

Je suis 100% ouvert à une autre solution si on peut la trouver.

**Comment by fuhrmanator** [comment]
Je ne veux pas briser le principe d'itération sans frontend, car c'est une validation partielle d'un système. C'est plus important de respecter ça que la séparation des couches ou les tests. Pour cela je vais fermer ce billet.

Aussi, la question de gens qui ne font pas de tests, ils ont un squelette, une activité dans le lab0 pour en créer et une pénalité s'ils font pas de tests à chaque itération. Peut-être que les tests dans la première itération ne sont pas supers, mais ils vont perfectionner ça j'espère.

J'aime beaucoup tous les points mentionnés (ex. variables dans le modèle pour contrôler les vues, etc.). Ce sont des instances d'antipatrons du squelette. Il serait super de les documenter (je vais créer un autre billet pour ça).
