### ISSUE TITLE
Vérifier respect architecture en couche.

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#46]
typescript router code change Bonjour Alexandre, je crois que tu as raison, les PUG utilisent des objets dans la version que nous vous avons donné.  C'est le genre de problème que cause le développement du front-end et du backend dans le même framework de développement.  Il aurait fallu créer deux projets distinct. Un pour le front-end, et un pour le backend.  Ainsi nous aurions été obligé d'utiliser des types primitifs.  Donc la solution actuel sera problèmatique si on veut remplacer la couche présentation par une couche mobile....  Vous ne serez pas pénaliser pour l'utilisation d'objets dans vos PUG.

**Comment by fuhrmanator** [comment]
Est-ce la même chose que https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/issues/6 ?

**Comment by yvanross** [comment]
Controleurs retourne maintenant du  JSON.

**Comment by yvanross** [comment]
Oui c’est la même chose.
Issue No 6 est maintenant fermé.

Yvan Ross, ing., M. Ing.
yvan.ross@gmail.com
https://www.linkedin.com/in/yvanross/
Gestion de projets RossY inc.
514-797-8894

**Comment by fuhrmanator** [comment]
> Controleurs retourne maintenant du JSON.

Savais-tu que sur le commit d'un changement, tu peux utiliser un commentaire comme "closes #x" et ça close le issue (en plus il y a une trace au changement). 

À propos de https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/e675bb45258d7c190278c55aa6d0cbebcbf4f3d9/src/core/JeuDeDes.ts#L26 je pense qu'il faut se poser la question sur l'encapsulation. Est-ce que `stringify` retourne toutes les infos (même privées) de l'objet Joueur? Je ne pense pas que ce soit une bonne idée de démasquer tout (en principe). Je sais que Joueur n'est pas si compliqué, mais le squelette est un exemple de bonne pratique.

**Comment by fuhrmanator** [comment]
Je précise - il n'y a pas vraiment de contrôle d'accès en JavaScript. Je fais une branche pour proposer une façon de faire.

**Comment by fuhrmanator** [comment]
Aussi, `getJoueurs()` fonctionne mal je dirais dans cette version (quand je lance le jeu je vois plein de joueurs non existants). Cette méthode a besoin de test, même si cela n'est pas une opération système.

**Comment by fuhrmanator** [comment]
Je vais l'ajouter à la branche aussi.

**Comment by yvanross** [comment]
On peut utiliser stringify avec un filtre mais je voulais garder ça le plus simple possible.

**Comment by yvanross** [comment]
Si tu veux faire une branche pour l'authentification, il faudrait faire un nouvel issue.  Pour le "closes #x" je sais mais j'ai rarement utilisé.

**Comment by Olon11** [comment]
Le routeur retourne toujours du JSON. Si une méthode .toJSON() n'est pas présente dans la classe, l'objet sera converti en JSON automatiquement. Seules les propriétés seront transmises.

**Comment by fuhrmanator** [comment]
> Le routeur retourne toujours du JSON. Si une méthode .toJSON() n'est pas présente dans la classe, l'objet sera converti en JSON automatiquement. Seules les propriétés seront transmises.

Effectivement. Si les propriétés sont privées, elles seront "_x" dans le JSON. La pratique d'utilise `toJSON` est expliquée à https://github.com/Microsoft/TypeScript/issues/16858 -- j'ai changé `Joueur.ts` pour avoir cette méthode dans la nouvelle branche dont j'ai fait un PR.

**Comment by fuhrmanator** [comment]
#47 résout le problème d'accès aux objets du domaine
