### ISSUE TITLE
Ajouter tests unitaires pour classes du domaine

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#49]
Faire des tests séparés (unitaires) pour les classes du domaine, comme Dé, Joueur, JeuDeDés.

**Comment by Olon11** [comment]
J'ai réaliser un projet avec les deux types de tests et je pourrais partager ma configuration pour Jest

**Comment by Olon11** [comment]
Je propose aussi l'utilisation des tests paramétriques pour les tests unitaires. C'est utile pour valider la gestion des exceptions des classes du domaine.

**Comment by yvanross** [comment]
la couverture de test est déja à 100%

**Comment by fuhrmanator** [comment]
C'est une bonne idée de faire les deux (même s'il y a 100% de couverture): 
https://www.geeksforgeeks.org/difference-between-unit-testing-and-integration-testing/ 

Par exemple, je pourrais tester (unit test) JeuDeDés en sachant qu'elle utilise un Map pour les Joueurs. La classe Dé en sachant qu'elle utilise `Math.random()`, etc.
Je peux tester une nouvelle classe de domaine avant que la fonctionnalité qui l'utilise soit mise en place (routeur, view, etc.)

Ce n'est pas super grave pour LOG210 -- on devrait enseigner la différence dans le cours de test et maintenance, mais j'aime donner on bon exemple de projet.

**Comment by Olon11** [comment]
L'objectif n'est pas d'améliorer la couverture de tests, mais d'utiliser les tests les plus pertinents pour chaque élément. Les tests unitaires valident mieux les classes du domaine et les tests d'API valident mieux les opérations système

**Comment by yvanross** [comment]
Tests unitaires ajoutés.
