### ISSUE TITLE
Documenter les antipatrons du squelette

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#51]
Ce billet sert à documenter les "antipatrons" du squelette. @Olon11 a déjà mentionné dans #41 l'utilisation de variable dans le modèle pour se souvenir du dernier cours sélectionné. 

Je voudrais en savoir plus ici, même avec les bouts de code. Je propose qu'on les documente sur un wiki et on propose des refactorisations (solutions). 

Souvent ce genre de truc sollicite beaucoup d'interaction en classe lorsqu'on les présente.

**Comment by fuhrmanator** [comment]
Il y a déjà deux antipatrons mentionnés dans https://log210-cfuhrman.github.io/log210-valider-architecture-couches/:

- instancier un objet du domaine dans le frontend (`new Devoir()`)
- route handler (avec arguments de requête et réponse HTTP) dans une classe du domaine (`Université`)

**Comment by Olon11** [comment]
Le premier antipatron a été documenté : [Vue sans route d'API](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/wiki/Vue-sans-route-d'API)

**Comment by fuhrmanator** [comment]
> Le premier antipatron a été documenté : [Vue sans route d'API](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/wiki/Vue-sans-route-d'API-(endpoint))

Voici une rétroaction de la part d'un étudiant
[LOG210_wiki.pdf](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/files/6794300/LOG210_wiki.pdf)

**Comment by Olon11** [comment]
Merci. J'ai effectué les modifications.

**Comment by yvanross** [comment]
Je ferme a moins que vous ayez d'autre anti-patron à documenter.
