### ISSUE TITLE
Modifier la section "Couplage" du Squelette

### ISSUE THREAD

**Issue by TheBigBear1** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#52]
Lien utile: https://github.com/cc-yvanross/s20211-log210-03-lab1-s20211-log210-03-lab1-team09/blob/master/README-squelette.md#couplage-souhaitable-entre-la-couche-pr%C3%A9sentation-et-la-couche-domaine

**Comment by fuhrmanator** [comment]
Bonjour @TheBigBear1 

Je n'ai pas compris ce issue, ni l'issue #53 - veux-tu donner plus de contexte STP?
