### ISSUE TITLE
Modèle de données GIFT

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#55]
Est-ce qu'on veut traduire le modèle de données?
Est-ce qu'on veut ajouter le type de question « missing word »?

**Comment by fuhrmanator** [comment]
Faire une traduction va juste créer un artefact de plus à faire évoluer lorsque le premier évolue... je viens de corriger une erreur avec la "Essay question" dans https://github.com/fuhrmanator/GIFT-grammar-PEG.js qui avait une réponse dans le modèle tandis qu'une vraie question ne définit aucune réponse (car c'est impossible de "corriger" une Essay question).

**Comment by fuhrmanator** [comment]
C'est un TODO pour le projet GIFT-Peg.js. Personne ne m'a demandé de supporter ce type de question encore dans le parser :)

**Comment by Olon11** [comment]
Je vois. On peut ferme l'issue dans ce cas
