### ISSUE TITLE
Les fichiers MD et PUML doivent être classés dans docs

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#57]
Les gabarits de rapport et les instructions devraient être dans docs et non pêle-mêle à la racine du projet

**Comment by Olon11** [comment]
Aussi, il y a deux gabarits de rapport (à la racine et dans docs)

**Comment by fuhrmanator** [comment]
> Aussi, il y a deux gabarits de rapport (à la racine et dans docs)

@yvanross pourrais-tu clarifier lequel on est censé utiliser?

**Comment by Olon11** [comment]
Y a-t-il des scripts qui ne vont plus fonctionner si on déplace des fichiers?

**Comment by yvanross** [comment]
Déja déplacé.

**Comment by fuhrmanator** [comment]
Il y a toujours des fichiers MD et PUML dans la racine.

**Comment by Olon11** [comment]
CONTRIBUTING.md doit être à la racine du projet pour que GitHub le prenne en compte.

**Comment by yvanross** [comment]
C'est déplacé.
