### ISSUE TITLE
Suggestion : remplacer Travis CI par Github Actions

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#59]
Cela permet de tout garder sur GitHub (un outil de moins). J'ai un script qu'on peut utiliser pour changer facilement

**Comment by Olon11** [comment]
L'intégration continue fonctionnerait lorsque les étudiants vont cloner le squelette. Il faudrait modifier les exigences pour en tenir compte

**Comment by fuhrmanator** [comment]
Pourrais-tu en faire un branche avec le script? Je voudrais bien essayer.

**Comment by Olon11** [comment]
C'est fait. Voir la PR que j'ai liée.

**Comment by Olon11** [comment]
@fuhrmanator Je propose la modification suivante pour l'exigence S2. Aussi, le badge dans le squelette a disparu. Je peux l'ajouter dans le README.

> Les décisionnaires de SGA insistent pour des technologies d'intégration continue avec GitHub Actions.
>
> **Note:** pour réaliser cette exigence il faudra autoriser l'outil [coveralls.io](https://coveralls.io) à accéder à votre dépôt et mettre à jour le badge de couverture. Il n'est pas nécessaire de modifier le flot de travail GitHub Actions.
>
> 0,25 points

**Comment by fuhrmanator** [comment]
Le badge n'est pas grave (il ne fonctionne plus lorsqu'on va cloner le projet, n'est-ce pas?).

J'aime l'exigence. Mais est-ce possible avec un dépôt privé?

**Comment by Olon11** [comment]
Effectivement, le bade ne fonctionnera plus. Pour coveralls, il faut avoir le [GitHub Student Developper Pack](https://education.github.com/pack). Je vais l'indiquer :

> Les décisionnaires de SGA insistent pour des technologies d'intégration continue avec GitHub Actions.
>
> **Note: **pour réaliser cette exigence il faudra autoriser l'outil [coveralls.io](https://coveralls.io/) à accéder à votre dépôt et intégrer le badge de couverture. Pour utiliser coveralls.io, un membre de l'équipe devra s'inscrire au [GitHub Student Developer Pack](https://education.github.com/pack). Il n'est pas nécessaire de modifier le flot de travail GitHub Actions.
>
> 0,25 points
