### ISSUE TITLE
Accès de la couche présentation (App.ts) à la couche domaine (JeuDeDes.ts)

### ISSUE THREAD

**Issue by NicolasBeaudet** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#6]
Index.pug génère le html a partir d'un objet Javascript créer directement à partir d'une instance d'un objet agrégé dans JeuDeDes.ts

Dans App.ts :

router.get('/', (req, res, next) => {
      let messages = res.locals.has_flashed_messages() ? res.locals.get_flashed_messages() : [];
      res.render('index', { title: 'Jeu de dés', flashedMessages: messages, _**joueurs: 
      Array.from(jeuRoutes.jeu.joueurs.values())**_});
});

Bien que cet utilisation d'Express avec Jade soit rapide et facile, elle n'est pas cohérente avec les principes GRASP (La couche présentation ne devrait pas interagir avec la couche de domaine).

**Comment by fuhrmanator** [comment]
OK - une solution serait d'imaginer un genre d'opération système dans `JeuDeDes` qui évite que `App.ts` accède aux classes `Joueur`. 

Il s'agit du principe "ne pas parler aux étrangers" ou bien la Loi de Déméter.  

Puisqu'il y a le contrôle d'accès dans TypeScript:

```TypeScript
export class JeuDeDes {
    // classe contrôleur GRASP

    // map des Joueurs
    private joueurs: Map<string, Joueur>;
    private d1 : De;
    private d2 : De;
...
```
Ce qui va empêcher de manipuler les attributs directement (c'est un exemple de pourquoi le contrôle d'accès est important). 

Si je fais `npm run build` j'obtiens:

```
src\App.ts(48,111): error TS2341: Property 'joueurs' is private and only accessible within class 'JeuDeDes'.
TypeScript: 1 semantic error
```
Ceci, parce que je ne veux pas que d'autres classes accèdent à ces aspects.

Ensuite, on n'a que à faire une fonction _stable_ (selon _Protection des variations_, comme une opération système) pour fournir la même information qu'utilise `App.ts`. Par exemple, dans `JeuDeDes.ts` on ajoute une méthode:

```TypeScript
    public getJoueurs() {
        return Array.from(this.joueurs.values());
    }
```
qui crée le tableau de Joueur pour la couche présentation. 

Puis, dans `App.ts` on change le code à

```TypeScript
      res.render('index', { title: 'Jeu de dés', flashedMessages: messages, joueurs: jeuRoutes.jeu.getJoueurs()});
```

Le dernier détail pour dire qu'on a vraiment séparé les couches... Est-ce que le template PUG utilise la classe `Joueur.ts`? Oui et nom. C'est la beauté (ou l'horreur?) de JavaScript:

```pug
      h3 Joueurs
      ul.entries
        each joueur in joueurs
          li.joueur
            strong(id=joueur.nom) #{joueur.nom}
            = ' '
            | tentatives: #{joueur.nbLancers}, réussites: #{ joueur.nbLancersGagnes }
            = ' '
            button.lancer(id=joueur.nom) Lancer les dés 
            = ' '
            button.terminer(id=joueur.nom) Terminer
``` 

Si je ne me trompe pas, ce qui se rend ici est un tableau d'objets JavaScript. Il est clair qu'il aura le format des attributs, etc. défini dans `Joueur.ts`, mais c'est un peu normal. La couche présentation doit connaître le format des objets de la couche domaine pour les présenter correctement. Dans LOG121, c'est le principe de la Vue qui "connaît" le modèle. Dans ce cas, on ne fait que afficher un objet, alors ce n'est pas une logique applicative.

Je vais faire un commit des changements bientôt.

**Comment by NicolasBeaudet** [comment]
Ne pas donner l'accès directement aux attributs de la classe est un pas dans la bonne direction. Par contre, je croyais que l'idée derrière la séparation en couche était que la vue ne devrait même pas connaitre la classe de modèle. Elle ne s'en sers pas directement puisque la classe de modèle est transformé en objet .json, mais comme vous dites, la vue *sait* de quoi elle à l'aire.

Je ne prétend pas être un expert en PUG ou avec express, mais il me semble que leurs fonctionnalités coïncide avec le patron MVVM. Une option pour remédier à cette situation pourrait être l'utilisation de viewModels et d'un médiateur, qui lui s'occuperait de gérer l'intéraction entre ces viewModels et les classes du domaine

D'un autre coté, je comprend aussi que cette option semble superflu pour le *Scope* de ce projet. Elle aurait peut-être plus de pertinence dans un projet à plus grande échelle comme le SGA par contre.

Qu'en penssez-vous?

**Comment by fuhrmanator** [comment]
Il y plusieurs forces en jeu. Sans rentrer dans les détails des variantes de mvc... C'est simplement model-view séparation.

 Le changement peut être dans la couche de présentation. Dans ce cas, passer par les façades facilite les changements.

Le modèle peut aussi changer. P.ex. un joueur peut avoir un avatar. Dans ce cas, il n'est pas facile de faire un design qui empêche que la couche présentation soit aussi touchée par ce changement. La vue doit connaître son modèle.

**Comment by yvanross** [comment]
Le controleur ne retourne que des string JSON.  Ce qui permet maintenant de respecter l'architecture en couche.
