### ISSUE TITLE
Les chiffres de la section Implémentation et tests ne sont pas à jour

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#60]
Dans [l'énoncé](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts#impl%C3%A9mentation-et-tests), le calcul n'est pas correct.

- [ ] Le calcul des points ne doit pas être individuel
- [ ] Le nombre de points à atteindre est 10 (pas 11)
- [ ] Le bonus devrait être uniformisé (avant, c'était 120%, mais j'avais proposé 110% pour éviter que les étudiants négligent le rapport)

**Comment by fuhrmanator** [comment]
> Dans [l'énoncé](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts#impl%C3%A9mentation-et-tests), le calcul n'est pas correct.
> 
> * [ ]  Le calcul des points ne doit pas être individuel
J'ai du mal à voir le problème avec "individuel" -- peux-tu être plus explicite (encore).

> * [ ]  Le nombre de points à atteindre est 10 (pas 11)

Le chiffre 11 n'est pas (plus?) dans l'énoncé (?)

> * [ ]  Le bonus devrait être uniformisé (avant, c'était 120%, mais j'avais proposé 110% pour éviter que les étudiants négligent le rapport)

Est-ce que la formule (plafond = 1.1) est juste? Le problème est avec le texte qui dit 120%?

> ![image](https://user-images.githubusercontent.com/7606540/124195204-f200fd00-da97-11eb-8c5f-792decfa1247.png)

**Comment by Olon11** [comment]
1. 

Dans la grille de correction, la formule est la suivante : ![](https://camo.githubusercontent.com/5376faebbefb8fa6d04980b14498ee37b27862683dbd85201076401b6af5ca1b/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f706e672f536f576b49496d676f4b71696f55314169544b654269724c4b30683870796d684b4f656c5a695f4b72445638496d656b414b723970496a487135386d444447747155486f494372423051613730303030)

Ça ne devrait pas être plutôt : d = (Sommation(nBPoints))/10. Pourquoi est-ce qu'on a besoin du nombre d'étudiants?

2.
Le chiffre 11 est dans la formule (celle ci-haut).

3.
Oui, exactement, il faudrait que le texte soit 110%. Pour éviter ce genre de problème, on peut juste retirer la formule et garder le texte.
