### ISSUE TITLE
Est-ce que l'implémentation est encore corrigée « tout ou rien »?

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#62]
Est-ce que l'implémentation est encore corrigée « tout ou rien »?

**Comment by fuhrmanator** [comment]
Peux-tu donner un exemple? Il y a une explication dans la partie implémentation: "Si une équipe ne réussit pas à répondre adéquatement à une exigence (fonctionnalité, tests, correspondance aux artéfacts), cette dernière ne sera pas utilisée dans le calcul."

**Comment by Olon11** [comment]
Par exemple, il y a des points pour les tests et la correspondance avec le code. Dans la correction tout ou rien, il faut avoir 100% à ces éléments pour qu'ils comptent dans le résultat final (donc, pas de points dédiés dans la grille de correction).

**Comment by fuhrmanator** [comment]
Je crois que ça prendra des exemples. @yvanross as-tu une idée de comment clarifier ça pour les étudiants et surtout les chargés le lab qui corrigent?

**Comment by yvanross** [comment]
C'est comme cela que la correction a été faite cette session.  Ca fonctionne ou ca ne fonctionne pas. On ne peut pas sauvegarder un devoir à moitié..
