### ISSUE TITLE
Le routeur est rempli de méthode dupliquées

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#63]
Retirer les méthodes inutiles

**Comment by fuhrmanator** [comment]
Il serait mieux d'avoir plus de détails, p.ex. est-ce https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/master/src/routes/JeuRouter.ts ? Quelles méthodes juges-tu dupliquées (est-ce le fait d'avoir les méthodes publiques/privées)?

**Comment by Olon11** [comment]
Ex.: demarrerJeu et _demarrerJeu. Je crois que le but était de séparer l'extraction des paramètres et la gestion des erreurs, mais, à mon avis, ça alourdit le code pour rien.

**Comment by fuhrmanator** [comment]
Il y avait des incohérences, c'est effectivement "extract method" pour les trucs plus longs. Je pense avoir amélioré la cohérence dans https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/commit/a3292c9ea7d2009be63718324717658e7d5c78ad

**Comment by Olon11** [comment]
Je ne vois pas le changement dans les méthodes. Elles sont toujours là

**Comment by fuhrmanator** [comment]
Elles sont toutes le résultat de "extract méthode". Je trouve cela correct selon le code smell "long method"

**Comment by Olon11** [comment]
Tu ne trouves pas que ça alourdit le code?

**Comment by fuhrmanator** [comment]
Ouf - ça dépend de combien de lignes font une "long method" -- c'est un aspect subjectif. Je ne suis pas en désaccord que ça alourdit d'avoir des 3 méthodes privées, mais la question est pénible de ce qui est moins lisible (avant ou après la refactorisation). 

Je crois que ce qui est arrivé est qu'une méthode avait une 20aine de lignes dans un `try` et on (@yvanross?) a appliqué extract method. Puis, pour être cohérent on a fait la même chose pour les 2 autres routes, mais le code était plus court dans ces cas. Cela peut sembler trop lourd, mais plus cohérent, plus lisible au moins sur l'aspect de la cohérence. 

Je crois qu'on fait un peu de [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality)?

**Comment by Olon11** [comment]
Je dirais que les routes sont un aspect important du squelette, alors probablement pas. Ce que je trouve étrange, c'est que les routes sont un extract method pour le Jeu. On a donc un extract method pour un extract method 🙃
