### ISSUE TITLE
Supprimer l'obligation d'utiliser Visual Studio Tech Debt Metrics

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#66]
Pour simplifier le travail de tous je propose de ne pas imposer cet outil dans l'évaluation.

**Comment by Olon11** [comment]
Je suis d'accord. Ou à la limite, autoriser une dette technique de B pour tenir compte de l'imprécision de ce genre d'outil.

**Comment by fuhrmanator** [comment]
J'ai installé l'outil et on doit permettre un accès à GitHub - je n'aime pas ça franchement que l'outil ne puisse pas travailler localement. C'est possiblement une question de confidentialité des travaux pour nos étudiants.

**Comment by Olon11** [comment]
Je ne crois pas que ce soit très grave du point de vue de la confidentialité. Il y a déjà plusieurs outils autorisés dans l'organisation.
