### ISSUE TITLE
Documenter l'initialisation de SGA

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#68]
classe de type Facade pour la sauvegarde local de toute les informations de SGB.
StudentStore, 
CourseStore
TeacherStore

**Comment by fuhrmanator** [comment]
EnrollmentStore (pour savoir rapidement les cours d'un étudiant ou les étudiants pour un cours)

On peut s'inspirer de [la RDCU des notes de cours pour le jeu de Risk](http://www.plantuml.com/plantuml/svg/ZLLDJzj04BrRuZ-Ck2H88Ig7NYoAG6bLGQ4WGji3uR3i3lR6zknsTqrBVr7pE_B7EdPYnvYF8aKRP-VDcpTlHiwX3yA5iiWZdscomea2V7Z8aK-dPHNPweHkXSmIPqfIqkJ6GN22F8UGmbOqW91g3_mHa0fIlvmE0Gdk30NG13yqAVFBCt13gF1Eb7ce82GAX2zE-ohd-6h2kAiKFO89AJeFkJ4P90v5JJRz_Xc6XSXOQEcGA-F3WByrSKDvZeghEZWwFOLlqq-Nqqvvs7ktqssfhy2Bf3heTPt7bC69AHs9_5NSxqmgc4gdRNWLTu5ibVDTOLqBWokHqwNWmUoDzxh3mfybaiGpz9Noermd19BdWIvYHD1IMy7-RyVdjtCCPqBJDWWFfWnUA-nXJh2yr3wh4VC-mSVbeWwetlr5BWAAJQBj9qwuIqsigGxBnr4RNuW7lqhiHSw4dL7Cv_wKbv6IqOmgx44DBY9PxG9MEjVDmExkmG7_XXXMiOWC0vnEqX33kZT07o0VcCeDS4Aoi8XNouBUVzzGgeX9QZB5N6gvyDVw1ZuyOZNtwBZMICN0gc7YbWkEbMv6JI6HkELVNYRsBK9IrGBRfW9xr9ImVRqDitN_fUvOtp0NaLqJ5ynRUVYSSEj6HOyzxhAr5JhkrzxNx8tePgx-w1vb5RvcbsOaK-4IT9CduSuyE7soWa6El5E6QBb0FoCrAFcLeMMgENGoFV_AxvLDeMPKJqkFlVw3ZGcoDK6svWwVaQjlncIA4Op7uvt7xiWtkTEskD8rtt--Xkthiwq-MmsfdT3mvVph-OjQxPkqrWDOJQ_Q3A7KqEwiB-JcejtKzk6Gd_X_u1y0)

**Comment by yvanross** [comment]
J'ai modifié SGB pour faciliter la récupération des informations. Le contrôleur de Façade SGB sera beaucoup plus facile à réaliser.

**Comment by fuhrmanator** [comment]
Je trouvais SGB correct (sauf l'absence de GroupeCours). 

La documentation d'initialisation est nécessaire parce que certains étudiants coupent les coins en rond et ne stockent rien (pas de cache) dans SGA. À chaque fois qu'ils veulent une info provenant de SGB, ils font la requête à SGB.
