### ISSUE TITLE
Points de l'exigence U1

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#73]
0,25 points, c'est vraiment peu pour cette exigence. Je mettrai idéalement 1 (au moins 0,5 points) puisque c'est plus long qu'intégrer un nouveau type question. Plus on intègre de cas d'utilisation, plus c'est long.

**Comment by Olon11** [comment]
Je me souviens qu'avant, c'était 1. Pour quelle raison le pointage avait-il changé?

**Comment by fuhrmanator** [comment]
@Olon11 je ne connais pas les codes par cœur - veux-tu donner plus d'infos STP?

**Comment by Olon11** [comment]
C'est [facteurs humains](https://github.com/profcfuhrmanets/log210-jeu-de-des-node-express-ts/blob/master/README-exigences-client.md#u1---facteurs-humains).

**Comment by fuhrmanator** [comment]
OK, j'ai un souvenir d'une équipe qui avait réalisé ça en mettant les bonnes classes CSS avec Bootstrap et c'est pour ça que c'est 0.25 points.

**Comment by Olon11** [comment]
C'est sûr, mais ça ne correspond pas à l'effort, comme écrit plus haut.

**Comment by yvanross** [comment]
Je suis d'accords pour l'effort.  L'objectif est de démontrer une exigence de type Usabilité.  Cela n'a aucun lien avec l'orienté objet. Donc s'il font ce choix, il font un mauvais choix puisque ce n'est pas payant.

**Comment by Olon11** [comment]
Si on ne veut pas qu'ils le fassent parce que ce n'est pas en lien avec la matière du cours, pourquoi avoir cette exigence?
