### ISSUE TITLE
Ne plus dépendre de gulp? Est-ce essentiel?

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#75]
Le package `gulp` amène beaucoup d'autres trucs parfois avec des failles de sécurité. Il a des avantages pour un projet avec beaucoup d'éléments, mais il complique aussi des choses (p. ex. générer les source map est plus compliqué). `tsc` a beaucoup d'options maintenant, alors peut-on simplifier le projet un supprimant `gulp`?

**Comment by Olon11** [comment]
Pas besoin de gulp pour la compilation et l'écoute des changements (watch). On peut déplacer les fichiers CSS et JS dans `dist` avec une commande Linux. La commande sera un peu longue, mais ça permet d'éliminer gulp.

Exemple que j'utilise dans un autre projet :

```json
"scripts": {
      "start": "node dist/index.js",
      "watch": "nodemon -L",
      "build": "tsc --project tsconfig.json && sass sass/styles.scss public/css/styles.css",
      "test": "jest --env=node --colors --coverage --runInBand test",
      "test:unit": "jest --env=node --colors --coverage unit",
      "test:integration": "jest --env=node --colors --coverage --runInBand integration"
}
```

**Comment by Leuchak** [comment]
ça permetrait aussi d'écrire le code coté client en TypeScript via la référence de projet
https://www.typescriptlang.org/docs/handbook/project-references.html

**Comment by yvanross** [comment]
C'est enlevé.

**Comment by yvanross** [comment]
ce n'est pas le bon projet.
