### ISSUE TITLE
Ajouter Madge à l'intégration continue

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#76]
Utiliser cette action : https://github.com/marketplace/actions/circular-dependency-check

**Comment by Olon11** [comment]
Aussi, supprimer madge.png du dépôt (possible de l'ajouter au .gitignore)

**Comment by fuhrmanator** [comment]
Tu connais bien GitHub actions et madge :)

**Comment by fuhrmanator** [comment]
STP faire un PR
