### ISSUE TITLE
Changements dans les figures de la section « Déploiement du système »

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#77]
- [ ] Remplacer « browser » par navigateur
- [ ] Augmenter le contraste du texte « Boite noire » Système de gestion des bordereaux

Pour le point 2, il est possible d'ajouter un fond clair derrière le texte ou une bordure claire autour de celui-ci.

**Comment by fuhrmanator** [comment]
Je vais aussi changer le nom à «Système externe» plutôt que boîte noire. 

Qu'en penses-tu?

![](http://www.plantuml.com/plantuml/svg/ZLBHJXmx37tFLrXSwG8IirBxM244b0fHLOWoxLEt3zwCTud8E6dYBA2AxsdvZlsnUZ8C2FhIaNR7TZp7vnpdC0icARqt-Tfnn8GzPBdpfF_9sLSdDlGnCB6qjKKFtngpBKuqkK1xZIlAqC3xgGrE7AxqGsCuT0HRvxXsAnGg2Nej9AOj-6a0u1aPlXt5w9r5SO5XcG8BUffpxzZrw5qMseipkftDETPnDxI07Q4-UWNEktCcWS8GgO2E_8XhR6roKRu3PZZzUcRk9pRjNPRDxvw6FaKQ1iwvKqYCCIaLb_CmOSuxxUdHxiJKiL1QeYMu34MqGN5hICdKXXS2RE3DhwByCtbDFKA_UP2hq0KVLaxhCOKOykQ1G2s6JvXwv4fLKKQy3WKNc0V2mPUHPNQgLytJlhQ69yTARnlgmq4ggMunH5CLT2qbvRtd_7CPHUSz-Bl8w1AzE26nioaZxkgOIl0U_i7JHKYwS2otrSxZtSfT0zZVV_g6ReKIqy41_6VhevecCTfwFWpS_nzJ2ZUDTSbwQZmjvG1QLMO9ehx0KpQEbo537ZEmLJUO8LRpI-UGHGjLq2kyv5PN2dWoKETnXK-eQVEGYnUK38EY7uzEDMRqIl6qlWukvPbvCaYTCNhhe39jTXvl2ho3euipkFpGVW5sQy82RypZKTE56sxg_lKtfTEQQssasLJ_df7CeKujlVy3)

**Comment by Olon11** [comment]
C'est bon!
