### ISSUE TITLE
Spécifier clairement qu'un Devoir n'est pas une question

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#83]

**Comment by fuhrmanator** [comment]
Je ne rappelle plus le contexte de ce billet -- peux-tu clarifier @yvanross

**Comment by yvanross** [comment]
Les etudiants mélangent souvent les devoirs et les questions. Il faudrait peut être ajouter un glossaire pour clarifier ces termes.

**Comment by yvanross** [comment]
c'est fait dans le glossaire.
