### ISSUE TITLE
Intégrer un truc pour simplifier les routages

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#87]
Que pensez-vous de cette approche: https://github.com/log210-cfuhrman/lab1-equipe07/blob/master/src/routes/AutoRouterBase.ts

Devrions-nous l'intégrer dans le squelette pour simplifier les routages?

**Comment by Leuchak** [comment]
Nous n'avons pas tous accès au code, est-ce que vous pourriez d'écrire le fonctionnement ?

**Comment by Olon11** [comment]
Je n'ai pas accès au code aussi. D'après le nom, je comprends que c'est une classe abstraite pour un routeur?

**Comment by fuhrmanator** [comment]
Sans montrer tout le code, avec `tplant` j'ai généré un PlantUML et j'ai copié la partie importante:

![image](https://user-images.githubusercontent.com/7606540/130282496-472a78ba-8a1e-42cd-8708-ebedd23625d0.png)

En gros, c'est une classe permettant de faire un bind automatique avec des méthodes ayant un certain format avec un caractère de soulignement - j'avoue que ce n'est pas super lisible (les trucs plus complexes).

**Comment by Olon11** [comment]
Pour une personne expérimentée, je crois que ça passerait. Par contre, pour un débutant, ça semble magique. Je crois qu'appeler la méthode est préférable pour l'apprentissage.

**Comment by Leuchak** [comment]
oula, les classes sont beaucoup trop grosse.
Leur méthode empèche le typage de Typescript de bien performé,
ce n'est pas une bonne méthode, et elle possède plusieurs points faible.
Il est préférable de ne pas montrer au élève ce genre de solution.

Ce qu'ils ont essayer de faire s'appele un "@decorateur". C'est ce qu'un développeur expérimenté utiliserait.
Le concept existe en typescript, son utilisation est facile, et beaucoup plus lisible.
Son implémentation dépasse le cadre du cours. Souhaitez-vous qu'on se penche tout de meme vers cette solution ?

**Comment by Leuchak** [comment]
Meme si l'implémentation est un peu plus avancé, son utilisation est simple.

**Comment by fuhrmanator** [comment]
> les classes sont beaucoup trop grosse.

Dans l'exemple, je suis d'accord. Mais la classe abstraite est petite et ça n'empêche pas concrétiser (faire des sous classes) différemment. 

> Leur méthode empèche le typage de Typescript de bien performé aussi.

C'est une bonne remarque, mais est-ce important pour le routage? Peut-être avec un @decorator et des types génériques on peut faire une variante plus propre?

Ce que je trouvais bien est le fait qu'on ne soit pas obligé d'appeler `bind` chaque fois. Pour l'API du système final, c'est beaucoup de "boilerplate" (code passe-partout). TypeScript existe pour réduire ce genre de code. DRY est un principe de conception. Imaginez la variante de ce lab sans la classe AutoRouterBase. 

Je sais que ça cache les façons de faire avec Express (mentionné par @Olon11), mais justement ça se justifie par le fait que LOG210 n'est pas censé être un cours axé web et on peut réduire la complexité de express en cachant un peu.

En même temps, je sais qu'en Java avec Swing on aurait beaucoup de `actionPerformed()` à coder et la complexité est plus due au nombre de fonctionnalités à réaliser qu'au cadriciel express. Swing était toujours un casse-tête quand les labs étaient en Java.

La classe `AutoRouterBase` deviendrait une certaine cadriciel "opinionated" (ce qui n'est pas toujours idéal sur le plan pédagogique puisqu'on simplifie). Par contre, si ça réduit la complexité Web du lab et ça permet aux étudiants de gagner du temps sur la partie "core" de l'application, je ne suis pas contre l'idée.

**Comment by Leuchak** [comment]
Utiliser une classe abstraite est une bonne idée, mais il est préférable d'évité d'utiliser la réflexion.
L'utilisation de @decorator me semble bien. Par contre je viens de lire que la fonctionnalité est
encore expérimental en TypeScript.
https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

**Comment by Olon11** [comment]
Je crois aussi que le décorateur serait préférable à la réflection. Vous spamez l'utilisateur qui s'appelle "decorator" 😂

**Comment by yvanross** [comment]
Ils ont déja tendance à mettre tout dans une même classe de routage avec un seul contrôleur.  Alors je ne crois pas que cela simplifierais le problème.

**Comment by fuhrmanator** [comment]
Je pense que ça simplifie les appels de `bind`, c'est un étudiant de
l'équipe 7 qui m'en a parlé car c'est son coéquipier qui la refactorisé
suite à énormément de code dupliqué. Je suis curieux pour la solution avec
Typescript decorator.
