### ISSUE TITLE
Fix unsupported tests name

### ISSUE THREAD

**Issue by Leuchak** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#88]
Le nom des tests doivent être static pour une meilleur compatibilité avec certains outils de développement.

![image](https://user-images.githubusercontent.com/21264237/130333471-7bf4dbc8-b6bf-4ac3-bcab-7477b8329c65.png)

**Comment by fuhrmanator** [comment]
Pourrais-tu préciser? Quels outils de développement? Je ne vois pas cette erreur de base avec le squelette et les outils comme Jest.

Je n'aime pas la solution puisque ça supprime de l'information sur le test (le test est configuré avec un nom). Je ne vois pas le problème.

**Comment by Leuchak** [comment]
Un tests devrait toujours avoir un nom statique, car il fera toujours la meme chose.
Nous n'avons pas besoin de connaitre le nom de l'utilisateur qui est testé, car c'est le comportement qui est testé et non l'utilisateur.

https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter

![image](https://user-images.githubusercontent.com/21264237/130365452-5c943066-6576-4df5-af51-ce19ff3d08ed.png)

**Comment by fuhrmanator** [comment]
Le nom est éventuellement important lorsqu'on essaie de faire des opérations avec des noms différents. P.ex. un groupe cet été n'avait pas de tests pour montrer la création de plusieurs EspaceCours avec les enseignants différents (leur design ne le supportait pas au fait). 

Alors, le nom de l'enseignant devrait apparaître dans le message, puisqu'il y en a au moins deux (différent). On utilise une variable non pas une variable, mais pour supporter le pattern "Literal Value" -- http://xunitpatterns.com/Literal%20Value.html -- c'est une bonne pratique pour cette raison.

Le "bogue" à corriger est peut-être de définir les strings comme `const` et non `let`?

**Comment by fuhrmanator** [comment]
Sinon, utiliser une chaîne template?

    `respond with successful first call for player ${testNom1}`

**Comment by Leuchak** [comment]
J'ai essayé les deux, l'outil lit directement le code pour détecté les tests.

**Comment by fuhrmanator** [comment]
j'ai refactorisé les tests et les noms sont tous utilisés - si ton outil n'aime pas ça, c'est un autre problème.
