### ISSUE TITLE
Séparer la view index.pug en layout

### ISSUE THREAD

**Issue by Leuchak** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#91]
La page index.pug contient la définition complete d'une page html.
Il est préférable de découper les vues en blocks pour simplifier la construction des pages web.

En lien avec #86, un meilleur découpage des page peut aidé les élève à construire des sites web complexe.

**Comment by fuhrmanator** [comment]
Je propose que ce soit une tâche pour le lab 0 - c'est une bonne idée, mais ça complique le squelette de base.
