### ISSUE TITLE
Affirmation erronée sur la maturité du modèle REST

### ISSUE THREAD

**Issue by ges134** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#99]
# Résumé

En tutorant une élève du cours, j'ai pu constater que le fichier `docs/Squelette.md` affirmait que le système _[...] est seulement REST niveau 2, mais ça n'empêche pas de modifier l'API pour qu'il soit REST niveau 3._ Or, en regardant les routes de l'API, on peut constater que l'information est erronée.

# Niveau de maturité

Selon la source indiqué dans `docs/Squelette.md`, le [_niveau 2 [...] défend l'utilisation de différents verbes basés sur les méthodes de requête HTTP._](https://restfulapi.net/richardson-maturity-model/#level-two) (traduction libre). Or, les points terminaux (_endpoints_) `/terminerJeu` et `/redemarrerJeu` ne respectent pas le verbe `GET` étant donné que leurs actions ne sont pas sécuritaire. En effet, les deux points terminaux suppriment des entités de l'API, ce qui modifie l'état du serveur. [MDN](https://developer.mozilla.org/fr/docs/Web/HTTP/Methods/GET). Conséquemment, le niveau de maturité 2 n'est pas respectée. 

En d'autres mots, ces deux points terminaux suppriment des entités et modifient l'état de l'API. Or, `GET` ne tolère pas la modification de l'état de l'API. En contrepartie, le verbe `DELETE` le permet.

# Corrections à apporter

Pour respecter les méthodes HTTP, `/terminerJeu` et `/redemarrerJeu` devraient être sur le verbe `DELETE` qui n'est pas sécuritaire [_selon la documentation_](https://developer.mozilla.org/fr/docs/Web/HTTP/Methods/DELETE).

**Comment by fuhrmanator** [comment]
Merci pour ce feedback détaillé. Je l'ai transféré au dépôt du squelette.

**Comment by ges134** [comment]
> Je propose de mettre le bon niveau (1), plutôt que d'alourdir le squelette avec la complexité REST. Ce n'est pas le but du squelette.

C'est comprenable. L'affirmation sera correcte par la suite aussi!
